// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "page": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/tekiomo-dark-side/goa-sample/design
// --out=$(GOPATH)/src/github.com/tekiomo-dark-side/goa-sample
// --version=v1.2.0-dirty

package client
