consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
host: localhost:8081
info:
  description: page
  title: Page
  version: ""
paths:
  /:
    get:
      description: トップページ
      operationId: pages#home
      produces:
      - text/html; charset=utf-8
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: home pages
      tags:
      - pages
  /complete:
    get:
      description: 完了ページ
      operationId: pages#complete
      produces:
      - text/html; charset=utf-8
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: complete pages
      tags:
      - pages
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  InternalServerError:
    description: Internal Server Error
  NotFound:
    description: Not Found
schemes:
- http
swagger: "2.0"
