// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "page": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/tekiomo-dark-side/goa-sample/design
// --out=$(GOPATH)/src/github.com/tekiomo-dark-side/goa-sample
// --version=v1.2.0-dirty

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// CompletePagesContext provides the pages complete action context.
type CompletePagesContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewCompletePagesContext parses the incoming request URL and body, performs validations and creates the
// context used by the pages controller complete action.
func NewCompletePagesContext(ctx context.Context, r *http.Request, service *goa.Service) (*CompletePagesContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := CompletePagesContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *CompletePagesContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/html; charset=utf-8")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// NotFound sends a HTTP response with status code 404.
func (ctx *CompletePagesContext) NotFound() error {
	ctx.ResponseData.WriteHeader(404)
	return nil
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *CompletePagesContext) InternalServerError() error {
	ctx.ResponseData.WriteHeader(500)
	return nil
}

// HomePagesContext provides the pages home action context.
type HomePagesContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewHomePagesContext parses the incoming request URL and body, performs validations and creates the
// context used by the pages controller home action.
func NewHomePagesContext(ctx context.Context, r *http.Request, service *goa.Service) (*HomePagesContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := HomePagesContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *HomePagesContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/html; charset=utf-8")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// NotFound sends a HTTP response with status code 404.
func (ctx *HomePagesContext) NotFound() error {
	ctx.ResponseData.WriteHeader(404)
	return nil
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *HomePagesContext) InternalServerError() error {
	ctx.ResponseData.WriteHeader(500)
	return nil
}
